### PR TITLE
Link with -O2 flag

### PR DESCRIPTION
**Pull request by kichikuou**
Currently, `cpp` files are compiled with the `-O2` flag, but no optimization flag is specified when linking.

This patch adds the `-O2` flag to link times, which significantly reduces code size (mainly due to JS minification).

### CODE REVIEW

**Comment by kichikuou** [comment]
As for speed, in my environment this made unpacking a 7z archive about 20% faster.

**Comment by use-strict** [comment]
LGTM. I will need to add some tests though before merging this, just to be safe.

**Comment by use-strict** [comment]
@kichikuou , please update your branch to the latest upstream master

**Comment by kichikuou** [comment]
> @kichikuou , please update your branch to the latest upstream master

Rebased and force-pushed.

**Pull request merged**
